# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d07a9b6e4deb092bbdd7f864306976469e7ea7b0eb4fd3169013fd67f855303317edc9f17234ef41aa9134ed7c9ad6ccd0bac0a88a8a253d3637a48323f008e

test:
  secret_key_base: 0368e7d1c3a787c746d22dd5748a4ea300f2ee2f178b0206763dd2c0170b2daa33130fecdfe94a28dc83c57256ee219f0b9ade3169c25cd030b7977fb7a32b56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
